### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'UNLINK') when updating packages

### ISSUE THREAD

**Issue by lumisong** [DonJayamanne/vscode-python-manager#87]
Type: <b>Bug</b>

Like issues: #72

### Environment data

- VS Code version: [1.86.2]
- Extension version (v1.2.4): 
- OS and version: [Ubuntu 20.04.6 LTS]
- Python version (miniconda): 
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: [...all new package]

### Expected behaviour

When executing `conda update --all` or updating packages through the extension interface, all installed packages should be successfully updated, or a message indicating that there are no packages to update should be prompted.

### Actual behaviour

When trying to update all installed packages through the Python Environment Manager extension in VS Code, a TypeError occurred, indicating that it cannot read the 'UNLINK' value of an undefined attribute.

### Steps to reproduce:

1. 
2. 
3. 

### Logs

///text
Error: Failed to get latest package information for /home/lumisong/桌面/mice_well_log_imputation/MICE_Conda/bin/python) TypeError: Cannot read properties of undefined (reading 'UNLINK')
at getOutdatedCondaPackages (/home/lumisong/.vscode/extensions/donjayamanne.python-environment-manager-1.2.4/out/client/extension.js:19757:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 1)
at getOutdatedPackages (/home/lumisong/.vscode/extensions/donjayamanne.python-environment-manager-1.2.4/out/client/extension.js:19122:46)
///
all logs

///
Debug: Searching for Conda packages with command conda,search,-f,p]}
> conda search -f p
Debug: Searching for Conda packages with command conda,search,-f,pa]}
> conda search -f pa
Debug: Searching for Conda packages with command conda,search,-f,pan]}
> conda search -f pan
Debug: Searching for Conda packages with command conda,search,-f,pand]}
> conda search -f pand
Debug: Searching for Conda packages with command conda,search,-f,panda]}
> conda search -f panda
Debug: Searching for Conda packages with command conda,search,-f,pandas]}
> conda search -f pandas
Debug: Installing package pandas into Conda:(/home/lumisong/桌面/mice_well_log_imputation/MICE_Conda/bin/python,MICE_Conda/bin/python) with command conda,install,-c,anaconda/pkgs/main,pandas==2.1.4,-p,/home/lumisong/桌面/mice_well_log_imputation/MICE_Conda,-y]}

>>>>>>>>>>>>>>>>>>>>>>>
Installing package pandas into Conda:(/home/lumisong/桌面/mice_well_log_imputation/MICE_Conda/bin/python,MICE_Conda/bin/python) with command conda,install,-c,anaconda/pkgs/main,pandas==2.1.4,-p,/home/lumisong/桌面/mice_well_log_imputation/MICE_Conda,-y]}

<<<<<<<<<<<<<<<<<<<<<<<

> conda update --all -d -p ./MICE_Conda --json
> conda list -p ./MICE_Conda --json
Debug: conda info --json: [
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "main",
    "channel": "anaconda/pkgs/main",
    "dist_name": "_libgcc_mutex-0.1-main",
    "name": "_libgcc_mutex",
    "platform": "linux-64",
    "version": "0.1"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "1_gnu",
    "channel": "anaconda/pkgs/main",
    "dist_name": "_openmp_mutex-5.1-1_gnu",
    "name": "_openmp_mutex",
    "platform": "linux-64",
    "version": "5.1"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h7b6447c_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "bzip2-1.0.8-h7b6447c_0",
    "name": "bzip2",
    "platform": "linux-64",
    "version": "1.0.8"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h06a4308_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "ca-certificates-2023.12.12-h06a4308_0",
    "name": "ca-certificates",
    "platform": "linux-64",
    "version": "2023.12.12"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 1,
    "build_string": "h1181459_1",
    "channel": "anaconda/pkgs/main",
    "dist_name": "ld_impl_linux-64-2.38-h1181459_1",
    "name": "ld_impl_linux-64",
    "platform": "linux-64",
    "version": "2.38"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h6a678d5_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "libffi-3.4.4-h6a678d5_0",
    "name": "libffi",
    "platform": "linux-64",
    "version": "3.4.4"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 1,
    "build_string": "h1234567_1",
    "channel": "anaconda/pkgs/main",
    "dist_name": "libgcc-ng-11.2.0-h1234567_1",
    "name": "libgcc-ng",
    "platform": "linux-64",
    "version": "11.2.0"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 1,
    "build_string": "h1234567_1",
    "channel": "anaconda/pkgs/main",
    "dist_name": "libgomp-11.2.0-h1234567_1",
    "name": "libgomp",
    "platform": "linux-64",
    "version": "11.2.0"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 1,
    "build_string": "h1234567_1",
    "channel": "anaconda/pkgs/main",
    "dist_name": "libstdcxx-ng-11.2.0-h1234567_1",
    "name": "libstdcxx-ng",
    "platform": "linux-64",
    "version": "11.2.0"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h5eee18b_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "libuuid-1.41.5-h5eee18b_0",
    "name": "libuuid",
    "platform": "linux-64",
    "version": "1.41.5"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h6a678d5_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "ncurses-6.4-h6a678d5_0",
    "name": "ncurses",
    "platform": "linux-64",
    "version": "6.4"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h7f8727e_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "openssl-3.0.13-h7f8727e_0",
    "name": "openssl",
    "platform": "linux-64",
    "version": "3.0.13"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "py310h06a4308_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "pip-23.3.1-py310h06a4308_0",
    "name": "pip",
    "platform": "linux-64",
    "version": "23.3.1"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h955ad1f_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "python-3.10.13-h955ad1f_0",
    "name": "python",
    "platform": "linux-64",
    "version": "3.10.13"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h5eee18b_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "readline-8.2-h5eee18b_0",
    "name": "readline",
    "platform": "linux-64",
    "version": "8.2"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "py310h06a4308_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "setuptools-68.2.2-py310h06a4308_0",
    "name": "setuptools",
    "platform": "linux-64",
    "version": "68.2.2"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h5eee18b_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "sqlite-3.41.2-h5eee18b_0",
    "name": "sqlite",
    "platform": "linux-64",
    "version": "3.41.2"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h1ccaba5_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "tk-8.6.12-h1ccaba5_0",
    "name": "tk",
    "platform": "linux-64",
    "version": "8.6.12"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h04d1e81_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "tzdata-2023d-h04d1e81_0",
    "name": "tzdata",
    "platform": "noarch",
    "version": "2023d"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "py310h06a4308_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "wheel-0.41.2-py310h06a4308_0",
    "name": "wheel",
    "platform": "linux-64",
    "version": "0.41.2"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h5eee18b_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "xz-5.4.5-h5eee18b_0",
    "name": "xz",
    "platform": "linux-64",
    "version": "5.4.5"
  },
  {
    "base_url": "http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main",
    "build_number": 0,
    "build_string": "h5eee18b_0",
    "channel": "anaconda/pkgs/main",
    "dist_name": "zlib-1.2.13-h5eee18b_0",
    "name": "zlib",
    "platform": "linux-64",
    "version": "1.2.13"
  }
]

Debug: conda update --all -d -p /home/lumisong/桌面/mice_well_log_imputation/MICE_Conda --json: {
  "message": "All requested packages already installed.",
  "success": true
}

Error: Failed to get latest package information for /home/lumisong/桌面/mice_well_log_imputation/MICE_Conda/bin/python) TypeError: Cannot read properties of undefined (reading 'UNLINK')
    at getOutdatedCondaPackages (/home/lumisong/.vscode/extensions/donjayamanne.python-environment-manager-1.2.4/out/client/extension.js:19757:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at getOutdatedPackages (/home/lumisong/.vscode/extensions/donjayamanne.python-environment-manager-1.2.4/out/client/extension.js:19122:46)
///

Extension version: 1.2.4
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 5.15.0-94-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.22GB (10.25GB free)|
|Process Argv|--unity-launch --crash-reporter-id b0b8be32-057c-4c03-bba6-fcec34664117|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
fegfb526:30961430
7j2b6412:30967274

```

</details>

**Comment by lumisong** [comment]
**Steps:**
1.
![image](https://github.com/DonJayamanne/vscode-python-manager/assets/42906894/807adff3-0364-4ef0-9d67-a3ab76faf663)
2.
![image](https://github.com/DonJayamanne/vscode-python-manager/assets/42906894/c14665d2-1118-4789-b7b9-84d09dc7217a)
**Notes:** 

The selected target for installation is pandas 2.1.4 (anaconda/pkgs/main), which will encounter the above issue.

However, if I choose to install from the source: pandas 2.1.4 (pkgs/main), this problem will not exist.
